### PR TITLE
fix: filtering and improve serilizer

### PR DESCRIPTION
**Pull request by martcl**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Banner filtering var broken og vi bør ikke sortere på custom modell properies. Prøvde å finne eksempler, men det er anbefalt å bare sortere på vanlige modell properties

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by thomsen85** [comment]
Funka ikke de propertyene?

**Comment by martcl** [comment]
Nope...

**Comment by martcl** [comment]
Men bruker propertiene for å sende dem til frontend. Da kan vi gi aktiv en annen farge eller noe sånt

**Comment by thomsen85** [comment]
💀 jaja, får ta å fjerne de då

**Pull request merged**
