### PR TITLE
fix(registration): fixed bug where an automatic bump would increase the event limit

### PR DESCRIPTION
**Pull request by Her0elt**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] Build (`make PR`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by olros — APPROVED** [review]
Ser litt hacky ut, men så lenge det funker så tenker jeg kjørr 🔥

**Review by Eirsteir — APPROVED** [review]
Det fungerer det her, men er som @olros sier, litt hacky. 

Er det en bedre løsning å ikke tillate admins å flytte folk opp i det hele tatt, men heller be dem flytte en bruker ned på ventelisten først?

Siden problemet oppsto først når admins flyttet folk opp fra ventelisten og vi hadde ingen sjekker for om arrangementet var fullt. Hvis det implementeres så slipper vi hele problemstillingen og det vil heller ikke kunne oppstå en situasjon der arrangementet plutselig er overbooket. 

Det er ingen skam å snu :)

**Comment by olros** [comment]
Ja, tenker det kan være lurt @Eirsteir . Men for å få inn en løsning litt kjapt tenker jeg vi merger denne og lager issue på ditt forslag

**Comment by Eirsteir** [comment]
Støttes 👍

**Pull request merged**
