### PR TITLE
finished events now appear in the correct order (newest first)

### PR DESCRIPTION
**Pull request by 1Cezzo**
"Tidligere arrangementer" events now appear in the correct order (newest first)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] API docs on [Codex](https://codex.tihlde.org/contributing) have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by 1Cezzo — COMMENTED** [review]
very good!

**Review by LeMiTam — COMMENTED** [review]
looks good

**Review by MadsNyl — CHANGES_REQUESTED** [review]
Dette funker. Men jeg ville anbefalt å gjøre om hele metoden til å bruke Django sin ORM til å filtrere ut alle events som har en registrering av bruker.

**Comment by 1Cezzo** [comment]
'Expired' va en property i Event klassen og ikke en boolean attributt, så kune ikke bruke ORM filtrering på den her, så måtte bruke if.. else her som en liten workaround

**Review by MadsNyl — APPROVED** [review]
Ser bra ut dette!

**Pull request merged**
