### PR TITLE
refactor(user): removed cell field from user model to comply with gdpr

### LINKED ISSUE #307: Fjern telefonnummer fra user
Ettersom vi ikke bruker telefonnummer til brukere per i dag og det ved å følge GDPR ikke er lov å oppbevare brukerinfo som ikke er nødvendig, så bør vi fjerne det feltet fra `user`-modellen.

### PR DESCRIPTION
**Pull request by Omjoa001**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Issue number: closes #307 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)
- [ x ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ x ] Format and lint (`make format` and `make flake8`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by olros** [comment]
Denne branchen inneholder endringer fra den andre pr'en din som må fjernes.

I tillegg bør vi dobbelsjekke med HS at de ikke ser noen behov for telefonnummer på brukere. Vi har aldri brukt dem de 2.5 årene jeg har vært i TIHLDE så de bør i såfall ha en god grunn for å beholde. Vil du sende dem en melding i "HS-Index" kanalen på Slack @Omjoa001 ?

**Comment by Omjoa001** [comment]
> Denne branchen inneholder endringer fra den andre pr'en din som må fjernes.
> 
> I tillegg bør vi dobbelsjekke med HS at de ikke ser noen behov for telefonnummer på brukere. Vi har aldri brukt dem de 2.5 årene jeg har vært i TIHLDE så de bør i såfall ha en god grunn for å beholde. Vil du sende dem en melding i "HS-Index" kanalen på Slack @Omjoa001 ?

Da skal jeg gjøre det

**Review by olros — APPROVED** [review]
📲

**Review by norgor — APPROVED** [review]
nice!

**Review by olros — APPROVED** [review]

**Pull request merged**
